### ISSUE TITLE
Use ddrace teams to have multiple games at the same time

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet-insta/ddnet-insta#26]
When playing 3on3s it can happen that spectators who want to play are forced to go on a new server. Would be much nicer if they could just join a team and play on the same server.

Will this work nicely with flags? Can this be implemented cleanly for spectators? Also for 0.7 vanilla clients?

**Comment by ChillerDragon** [comment]
Multiple games or not. Flags should live in a per team basis. As of right now teams have to be turned off so flags can not be yoinked by ghosts. This should be fixed so that teams can be turned on and one can quickly test something or do some fast capping while others are playing. This should be done even if nobody bothers to properly implement full game logic with winning rounds in a per team world.

**Comment by jxsl13** [comment]
we want them teams long term!

**Comment by lukure** [comment]
Well, I'm still not convinced by this idea. One reason for this is that it has never been a problem for anyone to play on different servers. It's a lot of work that will probably result in a lot of new bugs for a problem that doesn't exist. 
But there are also reasons that speak against it. The first is that I don't think this system will catch on. It would mean that you would always have to join a team to start a round (team 0 lobby must be unlimited, otherwise you can't join a team). In the team, however, there are no settings for how many people can join the team. This in turn would mean that you have to lock a team so that other people can't join. On the one hand, I don't think that many of the old people would still want to do that and on the other hand, it would make it almost impossible for new people to join a game or to understand how they can do it. But there will generally be problems with the server settings, whether it's the time limit, score limit or the map itself...
There would be some other problems with teams, but I think that should be enough for now.... :)=
And quite apart from the problems, there are also other reasons. It is often the case that a group wants to isolate itself from the other servers, for example to train. This becomes a lot more difficult. In addition, having several teams on one server would significantly downgrade the spectator experience.
These were just a few impressions, I don't think the whole thing is a really sensible idea. Then better invest time in a zcatch bridge ;D

**Comment by jxsl13** [comment]
zcatch is the most important feature anyway ;0.

**Comment by ChillerDragon** [comment]
Full round based game support for multiple teams is out of scope. A round end requires the world to be paused. I don't see how this can be achieved without a major refactor that would create a huge diff to ddnet and thus make updating impossible. Lerato also gave such thing a shot once I think, and it was quite an adventure. Also while having only one 1n1 server with 10 games instead of 10 servers with 2 players each would be really cool. It would bring lots of complexity to have proper games. Map votes would always be global (multi map would be way too crazy) which might already be a game breaker for most groups. But then also all settings like scorelimit and timelimit would either be shared or cause a huge complexity overhead.

Having flags in teams would be really cool for fastcap. And should be possible without any git conflict surface. But after having a quick look I have performance concerns. Once ddnet gets 128 player support there will be 128 ddrace teams. Which with the current flag code would mean that EVERY TICK we check 256 flags (red+blue*max_clients) and checking a flag state includes expensive operations such as 

```C++
int Num = GameServer()->m_World.FindEntities(pFlag->GetPos(), CFlag::ms_PhysSize, (CEntity **)apCloseCCharacters, MAX_CLIENTS, CGameWorld::ENTTYPE_CHARACTER);
```

So unless this is benchmarked or refactored I don't think its worth it too take such a big performance hit for fast cap in ddrace teams.

**Comment by ChillerDragon** [comment]
I implemented separate flags for every ddrace team in this [experimental branch](https://github.com/ddnet-insta/ddnet-insta/tree/insta_ddr_team_flags). I could not find a smart way to avoid making the code 256 times slower. I checked `htop` with 60 tees with and without this patch applied. Seems like the new flag code consumes on average 2% more cpu which is way too much for how little value it gives. Also the diff is quite big and the code becomes more complex and differs further from the vanilla flag code. So I do not think that feature is worth its down sides. Not planned for now.

One thing I did commit on the main branch is making ddrace teams safer. Grabbing flags and scoring is now impossible from teams other than team 0. This allows using the ddrace teams for chilling/goofing and testing without disturbing the main gameplay that happens in team 0. But everything else (gameplay or fast cap in ddrace teams) is out of scope.

Closing this issue as not planned.
